framework:
    validation:
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false


# App\Entity\Article:
#     properties:
#         title:
#             - NotBlank:
#                 message: Ne doit pas être vide !
#         intro:
#             - NotBlank:
#                 message: Ne doit pas être vide !
#         content:
#             - NotBlank:
#                 message: Ne doit pas être vide !
#         image:
#             - NotBlank: ~
#             - Url:
#                 message: L'URL doit être valide.